Traceback (most recent call last):
  File "run.py", line 83, in <module>
    experiment.config.update(vars(config))
  File "/home/amian/miniconda3/envs/IR/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 172, in update
    sanitized = self._update(d, allow_val_change)
  File "/home/amian/miniconda3/envs/IR/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 160, in _update
    parsed_dict = wandb_helper.parse_config(d)
  File "/home/amian/miniconda3/envs/IR/lib/python3.7/site-packages/wandb/sdk/wandb_helper.py", line 16, in parse_config
    params = _to_dict(params)
  File "/home/amian/miniconda3/envs/IR/lib/python3.7/site-packages/wandb/sdk/wandb_helper.py", line 45, in _to_dict
    elif "__flags" in vars(params):
TypeError: vars() argument must have __dict__ attribute